- blink/admissions_checklist_wrapper.php
> re-encode & after they are decoded.

- salesforce/php/register.php
Small Changes to Salesforce to provide more descriptive error messages
> Fix and refactor

- proof-points/php/proof-point-logic.php
I reworked the logic so instead of randomly grabbing from an array, it just randomizes the array to start.
This prevents the issue of hitting a never ending while loop.
> added a simple fix

- faculty-bios/php/faculty-bio-listing.php
- faculty-bios/twig/faculty-bio.html
It took me a bit to find my mistake. I didn't finish it up on friday, and I didn't catch that I committed something that broke it.
There are a ton of commits because i couldn't sync it due to permissions.
> Fix faculty bios

- events/php/calendar_rest.php
- events/php/event_feed.php
Added in logic to handle the new timezones from the tinker update
- New feature
No testing yet
> Added timezones

- news/php/news_articles_archive.php
The president announcements got a new Data Definition in cascade. This is to handle them in th e archive.
Delete any of these you don't use.
- New feature
- I pulled my branch on staging.bethel.edu. Looks great.
> add in the new logic

- faculty-bios/php/faculty-bio-listing.php
- faculty-bios/twig/faculty-bio.html
Added a fix for faculty bio listings. I noticed that the filter wasn't properly generating the job titles.
- Bug fix
- testing is a pain, which is why there are a ton of commits. Each commit has to be pulled on staging.bethel.edu/code.
> Fix faculty feeds

- news/php/news_article_feed.php
- news/php/news_article_gallery_feed.php
Jake asked me to add img-fluid as a class to the images on mybethel's community news and stories dashboard. This goes through our other news and stories code through cascade, so it needs to be updated in our cascade-php repo.
- New feature
- I pulled my branch on staging to test. It seemed to work great.
> Add mybethel news class

- news/php/news_articles_archive.php
The archives were semi broken. The problem was I added a snippet to fix it for the news/story update, but I didn't realize it was an array of arrays (I thought it was just an array).
I moved the code snippet to fix the problem
- Bug fix
- I tested on staging. I was able to get both the news archive and the prez annz archive to work properly.
> Fix prez annz 

- events/php/event_feed.php
Judd requested that events that were running over many days would show up in the event feeds as one event per day. This makes those changes.
Fixes ITS-219128
- New feature
I made the changes and looked at many event feeds on staging.bethel.edu and they looked like how Judd wanted. I asked Judd if he liked the format I had and he seemed to.
> Event feed issue final

- news/php/mybethel_news_feed.php
Fixes issue with myBethel home page news feed.
https://jira.bethel.edu/browse/ITS-224279
Delete any of these you don't use.
- Bug fix
Tested on staging and was able to load the news feed locally.
> News Feed Fix

- events/php/event_feed.php
Reverts betheluniversity/cascade-php#89
> Revert "Fix Sorting of events"

- events/php/event_feed.php
Reverts betheluniversity/cascade-php#90
> Revert "Revert "Fix Sorting of events""

- news/php/blog_article_feed.php
- news/twig/blog_post_feed.html
Requested by [ITS-226074](https://jira.bethel.edu/browse/ITS-226074)
Creates a feed of blog post teasers for use with Cascade on www.bethel.edu. The feed draws from the blog's auto-generated [Wordpress Feed](www.bethel.edu/blog/feed).
Delete any of these you don't use.
- New feature
Please briefly describe the tests that you ran to verify your changes.
- Using the actual blog feed, I tested all the different aspects of the data definition to ensure they worked properly and would change the output of the feed accordingly. 
> Blog feed rss

- news/php/news_article_gallery_feed.php
Commented out the code that made sure our coronavirus article was 3rd on the homepage
- New feature
Tested on staging.bethel.edu
> Removed Featured Covid-19 article from bethel.edu homepage

- .gitignore
- salesforce/php/program_licensure.php
- salesforce/twig/program_licensure.html
Runs the licensure information tables at /academics/program-licensure
Fixes # https://jira.bethel.edu/browse/ITS-234159
- New feature
Please briefly describe the tests that you ran to verify your changes.
Tested on the Staging site.
> Jj program licensure

- salesforce/twig/program_licensure.html
Add Comments
- New feature
Please briefly describe the tests that you ran to verify your changes.
- Tested in Staging
> add comments popup

- adult_programs/courses.php
Please include a summary of the change(s) and which issue is fixed. Please also include relevant context.
Fixes # [ITS-244753](https://jira.bethel.edu/browse/ITS-244753)
Delete any of these you don't use.
- New feature
On Staging
> add courses organized by year and term

- salesforce/php/course_offerings.php
- salesforce/twig/course_offerings.html
Added a mock cart to the course offerings page that sends desired courses through to the Salesforce page as a 'courses' parameter so they will be checked when the user gets there.
> add cart to course offerings

- salesforce/php/create_account.php
- salesforce/twig/create_account_form.html
Fixed an issue with the form when an external account was already logged in through CAS.
> Jj_external_logged_in

- .gitignore
- salesforce/php/course_offerings.php
- salesforce/twig/course_offerings.html
add groupings and hide descriptions and sort
- Small Change
- New feature
Locally and on XP and on Prod
> add groupings and hide descriptions and sort

- faculty-bios/php/faculty-bio-listing.php
- faculty-bios/twig/faculty-bio-swiper.html
Added Faculty bio info for new departmental pages
Fixes # (issue)
- New feature
This has been tested by myself and Marketing on staging.bethel.edu
> Faculty courses swiper

- program-search/php/catalog-table.php
Allow "See Plans" link on new major minor pages
Fixes # https://betheluniversity.atlassian.net/browse/ITS-262317
- New feature
XP and Prod
- [] I have made corresponding changes to the documentation
> Allow "See Plans" link on new major minor pages

- faculty-bios/php/faculty-bio-listing-v2.php
fixes https://betheluniversity.atlassian.net/browse/ITS-267101
> Jj_bio_sorting

- .gitignore
- .vscode/launch.json
- info.php
Please include a summary of the change(s) and which issue is fixed. Please also include relevant context.
add a info.php file and a launch.json for vscode debugging
> add debug files

- general-cascade/metadata-check.php
> Jj_cas_revert
